### PR TITLE
Wire-up Unit Test coverage reports in GitHub

### PR DESCRIPTION
**Pull request by drosenberg123**
## Changes
- added pull_request to on:
- changed `push.yml` to `checks.yml` to more accurately reflect the use case
- added `ArtiomTr/jest-coverage-report-action@v2` from GitHub Marketplace
- added minimum Unit Test pass/fail thresholds based on current values
- minor linting tech debt (lines too long)

## Notes
- Unit Test failures will now block merging
- LIMITATION: currently this will cause a failure in a fork, although the report will still run; investigation and follow-on PR expected soon

### CODE REVIEW

**Review by mmoss — APPROVED** [review]
I like the annotations :) now we just need to use this as a baseline and start chipping away at getting more coverage!

**Review by anish-joy — APPROVED** [review]
LGTM!

**Review by mmoss — APPROVED** [review]
:shipit:

**Comment by slahav** [comment]
Thank you @drosenberg123, this is the first major step towards our goal - to provide good unit tests coverage for CAM.

**Pull request merged**
